### ISSUE TITLE
Menu.Item and Listbox.Option question

### ISSUE THREAD

**Issue by grind-t** [armchair-traveller/sashui#2]
HI! I really like the idea of using actions for headless components. I learned about it relatively recently from this [article](https://www.captaincodeman.com/headlessui-components-with-svelte). I just wanted to ask if there is any reason why Menu.Item and Listbox.Option are implemented as components instead of actions?
Thanks!

**Comment by armchair-traveller** [comment]
@grind-t ...why not?

Just kidding. This same great question... I've agonized it for days, over several weeks. I've long forgotten about it but now that you've mentioned it here we go again... (I could write 3 articles about this even)

Even the implementation in the library is a little hacky, but since it's internal code it doesn't really matter to the consumer.

There's many options I've considered, none of them attractive. It was a good idea to step away. The article you link offers a step back for me and I could even think of a way to make it even more efficient:

```svelte
<button class="group flex rounded-md items-center w-full px-2 py-2 text-sm"
  class:active={$item.delete}
  use:item={'delete'}
>Delete</button>
```

I'm not going to go deep into how this would be implemented but I imagine a proxy would be usable there. The action could be.... *drumroll* an action store.

Now let's go over what's in question:

```svelte
<Item let:active>
  <button class="group flex rounded-md items-center w-full px-2 py-2 text-sm"
    class:active
  >Delete</button>
</Item>
```

(Yes, we don't have to do `Menu.Item`, we can very well destructure the `Item` component out just fine)

In the first case, we must supply a name, then use that name as the key for checking if a particular item is active. Not going to go over `$active == name` because I feel that would end up being horrible ergonomically (probably why I threw it out at first), but just imagine repeating that same logic multiple times in a single menu item. At worst, it should be a function, since we're only interested in whether a particular item is selected.

In the second case, it's slightly less verbose and no name needs to be specified.

So there's your base difference. Just a simple explicit name. Of these two, which do you prefer? I think internally in sashui, both can be used and it wouldn't change most of the core logic. The real problem with names is naming conflicts (every item must be unique), and also having to name in this case is just a mental burden that brings no extra benefit.

And this is why I made a concession. I felt what Headless UI had there, that's the one time I had to admit they really got it right, even if it wasn't in Svelte. I couldn't come up with anything more concise with the same amount of power. Couldn't fault it. More importantly, it is one of the few components that doesn't introduce a new element but simply wraps one the consumer provides, which pretty much means we still have full control over the element. (though the hacky way I did things was just so we wouldn't have to `use:action` on each item's element explicitly)

An implementation detail: The `Item` component still comes from the menu factory, which means it utilizes similar mechanics to how an action uses closure to share state. 

Admittedly, there is one advantage to using names: You could now use that state everywhere else easily. I... don't know when that'd be a good idea. The `Menu.Item` implementation here has the same functionality, but it's a bit harder to use because you have the selected element itself.

Welp, hopefully nobody is asleep after reading that. Thanks for asking this, I'm definitely open to more discussion on this API. It does feel kind of icky that I raved about actions but ended having to use components somewhere down the line, but I'm just trying to make sure the API is as _svelte_ as possible.

**Comment by grind-t** [comment]
Pretty comprehensive answer, thanks. I think I can close the issue then.
