### ISSUE TITLE
Menu raises TypeError: Cannot read properties of undefined (reading 'selected')

### ISSUE THREAD

**Issue by michaelbelete** [armchair-traveller/sashui#3]
Hey @armchair-traveller 

I recently updated `sashui` to the latest version, and it's raising `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'selected')`

![image](https://user-images.githubusercontent.com/50682242/186970186-16da2e74-d04c-4d16-a8c1-df51cb809fac.png)

## steps to reproduce
- Create a new svelte project 
       `npm create svelte@next my-app`
       `cd my-app`
       `npm i`
- Install `sashui`
       ` npm i sashui`
- copy/paste this sample code https://github.com/armchair-traveller/sashui#menu
- run the project
      `npm run dev`
      click on the open button and see the console in developer's tool

**Comment by ichigoyeh** [comment]
This has been fixed in v0.2.5

Apologies. This isn't to do with Svelte Kit. It was a disconnected refactor. Apparently a rename was packed into another commit but the other part wasn't committed yet (I updated the code as per bug fix with modal on another machine, didn't come back to laptop to commit this fix).

Thanks for the detailed repro & filing the issue. Everything has been committed so this specific version should be stable.

**Comment by armchair-traveller** [comment]
This has been fixed in v0.2.5

Apologies. This isn't to do with Svelte Kit. It was a disconnected refactor. Apparently a rename was packed into another commit but the other part wasn't committed yet (I updated the code as per bug fix with modal on another machine, didn't come back to laptop to commit this fix).

Thanks for the detailed repro & filing the issue. Everything has been committed so this specific version should be stable. Future components shouldn't affect the existing ones.
